config/routes.rb
SampleApp4::Application.routes.draw do
 
    resources :users
    resources :microposts, :only =>[:create, :destroy]
    resources :sessions, :only => [:new, :create, :destroy]
 
 
  root :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/copyright', :to => 'pages#copyright'
  match '/privacy', :to => 'pages#privacy'
  match '/legal', :to => 'pages#legal'
  match '/help', :to => 'pages#help'
  match '/faq', :to => 'pages#faq'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/search', :to => 'pages#search'
  match '/search2', :to => 'pages#search2'
  match '/search3', :to => 'pages#search3'
  match '/search4', :to => 'pages#search4'
  match '/search5', :to => 'pages#search5'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
    attr_accessible :content
  belongs_to :user
  
  validates :content, :presence => true,
                      :length => { :maximum => 150}
  
  validates :user_id, :presence => true
      
      
       default_scope :order => 'microposts.created_at DESC'
       
        self.per_page = 10
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email
  
    has_many :microposts
  
  email_regexp = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, :presence => true,
                   :length => { :maximum => 50}
  
  validates :email, :presence => true,
                    :format => { :with => email_regexp},
                    :uniqueness => {:case_sensitive => false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  
  
  
  
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
 
  def create
    @micropost = current_user.microposts.build(params[:micropost])
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_path
    else
      render 'pages/home'
    end
  end

  def destroy
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
    
   end
  def legal
    @title = "Legal"
  end

  def contact
    @title = "Contact"
  end
  
  def copyright
    @title = "Copyright"
  end
  
   def privacy
    @title = "Privacy"
  end
  
  def help
    @title = "Help"
  end
  
  def faq
    @title = "FAQ"
  end
 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
    
  end

  def create
    user = User.find_by_email(params[:session][:email])
    
    if user.nil?
      flash.now[:error] = "Invalid email"
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_to user
    end
  end

  def destroy
     sign_out
     redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new # responds to get /users/new by rendering new.html.erb
    @title = "Sign up"
    @user = User.new
  end
  
  def create # responds to post /users and redirects to /user/i if successful or new.html.erb if not
    @user = User.new(params[:user])
    if @user.save
      redirect_to user_path(@user)
    else
      @title = "Sign up"
      render 'new'
    end
  end
  
  def show # responds to get /user/i by rendering show.html.erb
    @user = User.find(params[:id])
    @title = @user.name
  end
  
  def index # responds to get /users by rendering index.html.erb
    @title = "Current users"
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  
  def title
    base_title = 'Matts Project'
    if @title.nil?
       base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
  def logo
    
    image_tag("goku.gif", :alt => "Matts Project", :class => "round")
    
  end
  def banner
    "FOOD-METER"
  end

def wordwithnumber(words)
   words[rand(words.length)]
end



end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent[:remember_token] = user.email
    current_user = user
  end
  
  def sign_out
    cookies.delete(:remember_token)
    current_user= nil
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
      !(current_user.nil?)
  end
  
  def authenticate
     deny_access unless signed_in?
  end
  
  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page"
  end

  private
    def user_from_remember_token
      userEmail = remember_token
      User.find_by_email(userEmail)
    end
  
    def remember_token
      cookies[:remember_token] || nil
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li>
			<%= link_to "Home", root_path %>
			</li>
			<li>
				<%= link_to "Legal", legal_path %>
			</li>
			<li>
				<%= link_to "Contact", contact_path %>
			</li>
			<li>
				<%= link_to "Copyright", copyright_path %>
			</li>
			<li>
				<%= link_to "Privacy", privacy_path %>
			</li>
		</ul>
		</nav>
</footer>

app/views/layouts/_header.html.erb
	<header>
	<%= link_to logo, root_path %>
  
	<nav class="round">
	
		
		
	</nav>
	 <b><center><%= banner %></center></b>
	    <div class="center"id="banner"><center><h15 class="center"><%= wordwithnumber(["The first soup was made of hippopotamus", 
	   	"Refried beans are only fried once", 
	   	"Apples are a member of the rose family",
	   	"Microwave cooking was discovered accidentally, when a chocolate bar melted in someone’s pocket",
	   	"The Popsicle was invented by an 11 year who kept it secret for 18 years.",
	   	"Dynamite is made with peanuts",
	   	"McDonald's feeds more than 46 million people a day - more than the entire population of Spain",
	   	"The first pizzas were just dough and tomato sauce - no cheese",
	   	"China produces more apples than any other country",
	   	"Lettuce is a member of the sunflower family",
	   	"Pizza hut are the world's largest user of cheese",
	   	"The only apple native to North America is the crabapple",
	   	"The average American consumes 28 pounds of bananas per year",
	   	"The most pizzas are delivered (and eaten) on New Year's Day, New Year's Eve, Halloween, Thanksgiving Eve, and Super Bowl Sunday",
	   	"Worcestershire sauce is made from dissolved fish",
	   	"The banana 'tree'is not really a tree, but a giant herb. The banana is the fruit of this herb.",
	   	"Many mass produced ice creams have seaweed in them",
	   	"The largest item on any menu in the world is the roast camel",
	   	"It is estimated that about three billion pizzas are sold in the United States every year.",
	   	"Pumpkins were once recommended for removing freckles and curing snake bites",
	   	"The toxic puffer fish delicacy called Fugu kills about 300 people per year",
	   	"In ancient China and certain parts of India, the meat from a mouse was considered a great delicacy",
	   	"Fast Food Hamburgers are made in huge factories",
	   	"The three dots in the Domino's Pizza logo represent the first three Domino's Pizza stores",
	   	"About half of American adults do not get enough vitamin A, a nutrient needed for healthy skin"])%></h15></center></div>
	<header>
		

app/views/layouts/_main.html.erb
<div class="right"id="banner2">


<nav class ="round" >

<li><%= link_to "Home", root_path %></li>
<li><%= link_to "Help", help_path %></li>
<li><%= link_to "FAQ", faq_path %></li>
<% if signed_in? %>
<li><%= link_to "Profile", current_user %> </li>
<li><%= link_to "Sign out", signout_path %> </li>

<% else %>
<li><%= link_to "Sign in", signin_path %> </li>
<% end %>
<% if signed_in? %>

<%= link_to image_tag("goku23.png") %>
	
	<% end %>

</nav>

</div>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
        <%= render 'layouts/stylesheets' %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="container">
			 <% flash.each do |key, value| %>
     <div class="flash <%= key %>">
         <%= value %>
     </div>
  <% end %>
            <%= render 'layouts/header' %>
					<section class="round">
			 <%= render 'layouts/main' %>
						<%= yield%>
					</section>
			<%= render 'layouts/footer' %>
		</div>
		
		
	</body>
</html>

app/views/microposts/_micropost.html.erb
<tr>
<td class="micropost">
<span class="content"><%= micropost.content %></span>
<span class="timestamp">
Posted <%= time_ago_in_words(micropost.created_at) %> ago.
<span>
</td>
</tr>

app/views/pages/contact.html.erb
<h1 id="cf">Contact Information via Web Form</h1>

<dt class="firstE"><strong>Address:</strong></dt>

<dd>FOOD-METER Offices<br />

2745 Ligeia Street<br />
San Antonio, Texas
78249</dd>

<dt><strong>Email:</strong></dt>
<dd><a href="mailto:matt_gamble07@hotmail.com">matt_gamble07@hotmail.com</a></dd>

<dt><strong>Telephone:</strong></dt>
<dd>555-555-1234</dd>

<dt><strong>Toll free:</strong></dt>
<dd>800-555-8008</dd>


<dt><strong>Webmaster:</strong></dt>
<dd><a href="mailto:csmgamble@hotmail.com">csmgamble@hotmail.com</a></dd><br/>

<p>Information requested on this form is voluntary and of users own vendetta. This information is being collected and anaylized to provide additional information requested by you and assists us here in improving our Internet site, of products and services.  Personal information that you provide is protected under the provisions of the <em><a href="http://laws.justice.gc.ca/en/P-21/index.html">Privacy Act</a></em>. The Act provides you with a right of access to your information.</p>

<p>When you are commenting about a specific page on our website, please include the URL (Web address).</p>

<p><strong>If intrested in a quick response, please ensure us with your e-mail address.</strong></p>
<form method="post" action="">
	 
<div class="fc-tbx"><label for="subject">Topic<strong>(required)</strong></label><br />
	<input type="text" size="41" maxlength="400" name="subject" id="subject" /></div>
	
<div class="fc-tbx"><label for="Comments">Comments and Questions <strong>(required)</strong></label><br />

<textarea name="Comments" id="Comments" rows="11" cols="50" ></textarea></div>

<div class="fc-tbx"><label for="Name">Name</label><br />
 <input type="text" size="41" maxlength="400" name="Name" id="Name" /></div>
 
<div class="fc-tbx"><label for="Title">Title</label><br />
 <input type="text" size="41" maxlength="400" name="Title" id="Title" /></div>
 

<div class="fc-tbx"><label for="Organization">Organization</label><br />
 <input type="text" size="41" maxlength="400" name="Organization" id="Organization" /></div>

 
<div class="fc-tbx"><label for="email">E-mail address</label><br />
 <input type="text" size="41" maxlength="400" name="email" id="email" /></div>
 
<div class="fc-tbx"><label for="Telephone">Telephone</label><br />
 <input type="text" size="41" maxlength="400" name="Telephone" id="Telephone" /></div>

<div class="fc-tbx"><input type="submit" value="Submit" /> <input type="reset" value="Clear" /></div>

app/views/pages/copyright.html.erb
<h1>Copyright</h1>

<p><b>Copyright notice </b><br/>

This website and its content is copyright of FOOD-METER - © FOOD-METER [2011]. All rights reserved.<br/>

Any redistribution or reproduction of part or all of the contents in any form is prohibited other than the following:
	
	<li>
    you may print or download to a local hard disk extracts for your personal and non-commercial use only
    </li><li>
    you may copy the content to individual third parties for their personal use, but only if you acknowledge the website as the source of the material
	</li><br/>
You may not, except with our express written permission, distribute or commercially exploit the content. Nor may you transmit it or store it in any other website or other form of electronic retrieval system.
</p>

app/views/pages/faq.html.erb
<h1>Frequently Asked Questions (F.A.Q.)</h1>


<h4>Q. What is a FOOD-METER?</h4>


<b>A.</b>
<p> A FOOD-METER lets you search for the
   food nutrition in a database and view the full nutritional content  (calories, carbs, fat, protein etc.)
	 of every single food that you eat or are ever thinking of eating. Having this information avaliable will 
	 help you to improve your weight, your health, and just your general knowledge of what you are putting into 
	 your body. </P>






<h4>Q. Is calorie a bad word?</h4>

<b>A.</b>
<p>No, it’s not at all just misunderstood! Most people who use the word calorie  don’t know what it means. 
Most people get scared at the mere notion of the word. </P>


<h4>Q. What exactly is a calorie?</h4>

<b>A.</b> 

<p>According to Merriam-Webster’s Collegiate Dictionary (11th edition), 
a calorie is “a unit equivalent to the large calorie expressing 
heat-producing or energy-producing value in food when oxidized in the body.” 
In other words, a calorie is a unit of energy released from  food you eat to power your body.</p>


<h4>Q. How are calories “burned”?</h4>

<b>A.</b> 
<p>The body needs energy from food—calories—to perform many functions, 
i.e. physical activity and exercise. However, 
the body also needs energy to function to do the most basic functions: to breathe, 
digest food, and maintain organs and systems.</p>


<h4>Q. How many calories should I eat each day?</h4>

<b>A.</b>  
<p>Short answer “enough.” The calories you consume must provide you with enough energy for 
your body to perform all necessary functions and activities—and bring about optimum health. 
The long answer is that the number of calories needed varies from person to person and depends
 on difrrent factors such as weight, amount of food consumed, sleep, stress and activity levels, age, and other 
 factors that affect metabolism. </p>


<h4>Q. Is it possible to eat too few calories?</h4>

<b>A.</b>  
<p>Yes you can. The most serious problem with low-calorie diets is that 
although they may be weight loss, it also can cause serious health problems. 
One common side effect of low-calorie diets is muscle breakdown, which can occur when 
the body doesn’t consume enough calories from protein. Especially vulnerable cause of this is the heart, 
a muscular organ. If a person does not consume a proper amount of calories each day, 
the heart muscle begins to breakdown, possibly leading to serious cardiac conditions (e.g., cardiac atrophy).</p>

app/views/pages/help.html.erb
<h1>Help</h1>

<p>This is a help page.</p>


<h4>Q. Where Do I signin/signup?</h4>


<b>A.</b>
<p> On the right sid eof the website is the sign in and sign up link</p>





<h4>Q. How do i look up calories?</h4>

<b>A.</b>
<p>Sign in and it will redirect you to where you can look up calories of what you ate </P>


<h4>Q. How do i contact the company?</h4>

<b>A.</b> 

<p>On the bottom of the website is a footer with a link to our contact infromation</p>

app/views/pages/home.html.erb
<h1 class="center" ><center>FOOD-METER</center></h1>




<p><h4>Lose The Guilt and Gain the Knowledge of FOOD!</h4>

<p>Sign up now and start keeping track of your weight!!!</p>


<p>New user? Click <%= link_to "here", signup_path %> to sign up FREE</p>


Browse through calorie and nutritional information with this easy to use our food meter and 
learn which foods and beverages work for your waistline and which ones are not goo for you.
So turn that frankenstein in the mirror into a frank-fine!!!

<%= image_tag("greekfood.jpg")%>

</p>






<% if signed_in? %>
<h4>
	Start Looking Up Food HERE!!!!<br/>
<%= link_to "Carbohydrates", search_path, :class => "button round"%><br/>

<%= link_to "Vegtables", search2_path, :class => "button round" %><br/>

<%= link_to "Fruits", search3_path, :class => "button round"%><br/>

<%= link_to "Dairy", search4_path, :class => "button round"%><br/>

<%= link_to "Meats And Beans", search5_path, :class => "button round"%><br/>
</h4>
<% end %>
<br/>

app/views/pages/related.html.erb
<h1>Related Websites</h1>


http://www.webmd.com/diet/healthtool-food-calorie-counter

app/views/pages/s1.html.erb
<p>Bread
	Calories 42
	<br/></p>
	


			<% if signed_in? %>

<%= link_to "Fruits", s2_path %>
<%= link_to "Veggies", s3_path %> 
<%= link_to "Dairy", s4_path %> 
<%= link_to "Meat", s5_path %> 
<% end %>

app/views/pages/s2.html.erb
<p>Apple
	Calories 93
	<br/></p>
	



			<% if signed_in? %>
<%= link_to "Carbs", s1_path %> 

<%= link_to "Veggies", s3_path %> 
<%= link_to "Dairy", s4_path %> 
<%= link_to "Meat", s5_path %> 
<% end %>

app/views/pages/s5.html.erb
<p>Steak
	Calories 224
	<br/></p>
	





			<% if signed_in? %>
<%= link_to "Carbs", s1_path %> 
<%= link_to "Fruits", s2_path %>
<%= link_to "Veggies", s3_path %> 
<%= link_to "Dairy", s4_path %> 

<% end %>

app/views/pages/search.html.erb
 <b><center><%= banner %></center></b>
 
<center> <h4>Carbohydrates</h4></center>
 
	 <p>Whole Wheat Bread(1 Slice)<br/>
	 	Calories 89
	 	</p>
	 	
	 	<p>White Bread(1 Slice)<br/>
	 	Calories 120
	 	</p>
	 	
	 	<p>Rice, Cooked/Boiled (1 Cup)<br/>
	 	Calories 169
	 	</p>
	 	
	 	<p>Pasta (3oz)<br/>
	 	Calories 112
	 	</p>
	 	
	 	<p>Cereal, Bran Flakes (3/4 Cup)<br/>
	 	Calories 96
	 	</p>
	  <center>	
<%= text_field "pressRelease", "text" %>
 <%= button_to"submit" %>

	<% if signed_in? %>
	<h4>
<%= link_to "Vegtables", search2_path, :class => "button round" %><br/>

<%= link_to "Fruits", search3_path, :class => "button round"%><br/>

<%= link_to "Dairy", search4_path, :class => "button round"%><br/>

<%= link_to "Meats And Beans", search5_path, :class => "button round"%><br/>
</h4></center>
<% end %>
	 	

app/views/pages/search2.html.erb
 <b><center><%= banner %></center></b>
 
 
 
	 <p>Tomato Fresh (med size)<br/>
	 	Calories 28
	 	</p>
	 	
	 	<p>Cucmuber Fresh (1/2 cup)<br/>
	 	Calories 8
	 	</p>
	 	
	 	<p>Potato baked peeled (1/2 cup)<br/>
	 	Calories 57
	 	</p>
	 	
	 	<p>Lettecue(1 cup)<br/>
	 	Calories 7
	 	</p>
	 	
	 	<center><%= text_field "pressRelease", "text" %>
 <%= button_to"submit" %>
	 	
	 	<% if signed_in? %>
	 	<h4>
<%= link_to "Carbohydrates", search_path, :class => "button round"%><br/>


<%= link_to "Fruits", search3_path, :class => "button round"%><br/>

<%= link_to "Dairy", search4_path, :class => "button round"%><br/>

<%= link_to "Meats And Beans", search5_path, :class => "button round"%><br/>
</h4></center>
<% end %>
	 	
	 	
	 	
	 	
	<header>

app/views/pages/search4.html.erb
 <b><center><%= banner %></center></b>
 
 
 
	 <p>Milk (8oz )<br/>
	 	Calories 78
	 	</p>
	 	<p>Yogurt (6oz)<br/>
	 	Calories 60
	 	</p>
	 	
	 	 <p>Slice of cheese<br/>
	 	Calories 94
	 	</p>
	 	<p>
	 	Ice Cream Bar Caramel coated w/nuts<br/>
	 	Calories 171
	 	
	 	</p>
	 	
	 	
	 	<center><%= text_field "pressRelease", "text" %>
 <%= button_to"submit" %>
	 	
	 	<% if signed_in? %>
	 	<h4>
<%= link_to "Carbohydrates", search_path, :class => "button round"%><br/>

<%= link_to "Vegtables", search2_path, :class => "button round" %><br/>

<%= link_to "Fruits", search3_path, :class => "button round"%><br/>



<%= link_to "Meats And Beans", search5_path, :class => "button round"%><br/>
</h4></center>
<% end %>
	<header>
		

app/views/pages/search5.html.erb
 <b><center><%= banner %></center></b>
 
 
 
	 <p>Chicken over roasted w skin (2 pices)<br/>
	 	Calories 156
	 	</p>
	 	
	 	<p>Tuna Fish (1/4 cup)<br/>
	 	Calories 126
	 	</p>
	 	<p>Prime Steak (3oz)<br/>
	 	Calories 221
	 	</p>
	 	
	 	<p>Peanuts (1/4 cup)<br/>
	 	Calories 50
	 	</p>
	 	
	 	<center>
	 	<%= text_field "pressRelease", "text" %>
        <%= button_to"submit" %>
	 	
	 	<% if signed_in? %>
	 	<h4>
<%= link_to "Carbohydrates", search_path, :class => "button round"%><br/>

<%= link_to "Vegtables", search2_path, :class => "button round" %><br/>

<%= link_to "Fruits", search3_path, :class => "button round"%><br/>

<%= link_to "Dairy", search4_path, :class => "button round"%><br/>

</h4></center>
<% end %>
	 	

app/views/pages/terms.html.erb
<h1>Terms and conditions template for website usage</h1>
Welcome to our website. If you continue to browse and use this website, you are agreeing to comply with and be bound by the following terms and conditions of use, which together with our privacy policy govern [business name]'s relationship with you in relation to this website. If you disagree with any part of these terms and conditions, please do not use our website.

The term '[business name]' or 'us' or 'we' refers to the owner of the website whose registered office is [address]. Our company registration number is [company registration number and place of registration]. The term 'you' refers to the user or viewer of our website.

The use of this website is subject to the following terms of use:

The content of the pages of this website is for your general information and use only. It is subject to change without notice. 
This website uses cookies to monitor browsing preferences. If you do allow cookies to be used, the following personal information may be stored by us for use by third parties: [insert list of information]. 
Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on this website for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law. 
Your use of any information or materials on this website is entirely at your own risk, for which we shall not be liable. It shall be your own responsibility to ensure that any products, services or information available through this website meet your specific requirements. 
This website contains material which is owned by or licensed to us. This material includes, but is not limited to, the design, layout, look, appearance and graphics. Reproduction is prohibited other than in accordance with the copyright notice, which forms part of these terms and conditions. 
All trade marks reproduced in this website which are not the property of, or licensed to, the operator are acknowledged on the website. 
Unauthorised use of this website may give rise to a claim for damages and/or be a criminal offence. 
From time to time this website may also include links to other websites. These links are provided for your convenience to provide further information. They do not signify that we endorse the website(s). We have no responsibility for the content of the linked website(s). 
Your use of this website and any dispute arising out of such use of the website is subject to the laws of England, Northern Ireland, Scotland and Wales. 

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> 
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <div class="field" >
    <%= f.text_area :content %>
  </div>
  
  <div class="actions" >
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<li><%= link_to user.name, user %></li>

app/views/users/index.html.erb
<h1>Current users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
  </tr>
<% end %>
</table>

<br />



<%= link_to 'Home', root_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>


<%= form_for(@user) do |f| %>
 <%= render 'shared/error_messages' %>
  <div class="field" >
    <%= f.label :username %>
    <%= f.text_field :name %>
  </div>

  <div class="field" >
    <%= f.label :email %>
    <%= f.text_field :email%>
  </div>
  
    

  <div class="actions" >
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Welcome To FOOD-METER</h1>
<h1><%= @user.name %></h1>
<p><strong>Account Infromation</p></strong>

<p><strong>This is your username</strong></p>
<p><strong>Name:</strong><%= @user.name %></p>

<p><strong>This is your password</strong><br/><br/>

<b>Email:</b>
<%= @user.email %>
</p>




<%= link_to "Home", root_path%>